### ISSUE TITLE
restructure bloated psy_tools package

### ISSUE THREAD

**Issue by alexpiet** [alexpiet/licking_behavior#139]
### For each function, I will clean it up in the following ways
- Move to a more appriopriate location, rather than `psy_tools`
   - `psy_visualization` is just for plotting. If there is any computation, it should go elsewhere. 
   - move analysis functions to `psy_analysis_tools`
- Use the project style to define fontsizes, colors, alphas, linestyles
- Use the clean-string functions for consistent names
- Use consistent save locations, and don't be afraid to make more subdirectories
- Make analysis operate on summary_table #145 
- Add clear documentation for each function, and add to overview #157 
   - Clear doc-string defines inputs/outputs, error checks
   - Top level functions are called in overview
   - Inner or helper functions are listed in the doc-string of the relevant top-level function
  
### Breaking this issue up into several topics:
- [x] Summary functions
- [x] ps.plot_manifest_by_stage
- [x] ps.plot_manifest_groupby
- [x] ps.scatter_manifest
   - put ROC vs hits in scatter by manifest. 
- [x] Compare versions. Very outdated. Should we preserve backward compatability?
- [x] Build model manifest. Part of #149
- [x] Clustering. Making separate issue #188 
- [x] PCA. Making separate issue #190
- [x] Mouse fits. Are fits better if you fit everything all at once? Is that worth preserving? Making separate issue #187
- [x] Move remaining functions around so they make more logical sense?
