### ISSUE TITLE
Updates to metric analyses

### ISSUE THREAD

**Issue by alexpiet** [alexpiet/licking_behavior#176]
I think this module was designed with the insight that a lot of model free metrics are independent of model fits, so we shouldn't bother to recompute things over and over again. But on revisiting this module it seems like everything is really set up around the model version, so its a lot of extra work to separate things by model free and model based. 

- `psy_metrics_tools`
   - Core metric computation
      - get_metrics()
      - annotate_licks()
      - annotate_bouts()
      - annotate_flash_rolling_metrics()
      - [x] `pm.classify_by_flash_metrics()` (addressed by #215)
      - [x] `pm.annotate_bout_start_time()` (addressed by #215)
      - [x] `pm.get_engagement_for_fit()` (addressed by #215)
   - [x] Single Session Analysis (addressed by #214)
      - `plot_all_metrics()`, iterates through sessions and calls "plot_metrics()" Should this be part of fit_session?
      - `plot_metrics_from_table(df, index)` Plots a single session from summary_df?? Should this operate on session_df?
      - `plot_metrics()`   crashes currently
      - `plot_metrics_old()`
      - `plot_2D()`
   - [x] Plots for population analysis (addressed by #212)
      - `plot_rates_summary()` just calls `plot_rates()`
      - `plot_counts_summary()`, just calls `plot_counts_summary()`  
      - `get_colors()` should be moved to pstyle
      - `get_clean_label()` should be moved to pstyle
      - `get_styles()` should be moved to pstyle
      - `plot_counts()` is this redundant with psy_visualization? If not, move to `pv`
      - `plot_rates()` is this redundant with `psy_visualization`? If not, move to `pv`
      - `build_metrics_df` is this redundant with summary_df? if not, merge into summary_df
      - `get_metrics_df` seems at least redundant with `build_metrics_df`
      - `plot_engagement_landscape` useful, need to update
- [x] `pm.get_clean_label()` and `pm.get_styles()` are redundant with `pgt.get_clean_string()` and `pstyle.get_style()` (addressed by #212)
- [x] Most things operate on a metrics df, should work on summary_df (addressed by #212)
- [x] Some functions work on a single session df, but its not clear this is session_df (addressed by #214)
- [x] overall for QC and stability. 
   - [x] #242 
   - [x] #244
   - [x] #245
   - [x] #213 
   - [ ] #142
   - [x] update documentation in `pm.get_metrics()`
